AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Tournament Rankings Processor Application Lambda and DynamoDb
Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: true
    
Resources:
  PlayerRankingsProcessorApplication:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: player-results-processor-app/src/
      Handler: app.playerResultsProcessorHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        PlayerTournamentResultsTable:
          Type: DynamoDB
          Properties:
            Stream: !ImportValue player-tournament-results-dynamoDB-stream-arn
            StartingPosition: LATEST                                                           
      Policies:    
      - DynamoDBCrudPolicy:
          TableName: player_rankings
      - DynamoDBStreamReadPolicy:
          TableName: player_tournament_results
          StreamName: !Select [3, !Split ["/", !ImportValue player-tournament-results-dynamoDB-stream-arn]]
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
Outputs:
  PlayerRankingsProcessorApplication:
    Description: Player Rankings Processor Application Lambda ARN
    Value: !GetAtt PlayerRankingsProcessorApplication.Arn
  PlayerRankingsProcessorApplicationIamRole:
    Description: Implicit IAM Role created for Player Rankings Application Lambda
    Value: !GetAtt PlayerRankingsProcessorApplicationRole.Arn
