name: Deploy Tennis Rankings Application Stack
on: 
  workflow_dispatch:
    inputs:
      s3-bucket:
        description: S3 bucket containing AWS Lambda binaries to deploy
        type: string
        required: true
jobs:
  deploy-player-tournament-results-app:
    name: Deploy Player Tournament Results Application
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}        
      - name: Deploy player tournament results app
        id: deploy-player-tournament-results-app
        uses: ./.github/actions/build-and-deploy-lambda
        with:
          application-name: player-tournament-results-app
          folder-name: player-tournament-results
          s3-bucket: ${{ inputs.s3-bucket }}
          s3-prefix: player-tournament-results
          has-api: 'true'       
      - name: Create Build Summary  
        run: echo "Player Tournament Results Application URL - ${{ steps.deploy-player-tournament-results-app.outputs.api-url }}" >> $GITHUB_STEP_SUMMARY
  deploy-player-rankings-app:
    name: Deploy Player Rankings Application
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}        
      - name: Deploy player rankings app
        id: deploy-player-rankings-app
        uses: ./.github/actions/build-and-deploy-lambda
        with:
          application-name: player-rankings-app
          folder-name: player-rankings
          s3-bucket: ${{ inputs.s3-bucket }}
          s3-prefix: player-rankings
          has-api: 'true'          
      - name: Create Build Summary  
        run: echo "Player Rankings Application URL - ${{ steps.deploy-player-rankings-app.outputs.api-url }}" >> $GITHUB_STEP_SUMMARY
  deploy-player-results-processor-app:
    needs: [deploy-player-tournament-results-app, deploy-player-rankings-app]
    name: Deploy Player Results Processor Application
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}        
      - name: Deploy player results processor app
        id: deploy-player-results-processor-app
        uses: ./.github/actions/build-and-deploy-lambda
        with:
          application-name: player-results-processor-app
          folder-name: player-results-processor
          s3-bucket: ${{ inputs.s3-bucket }}
          s3-prefix: player-results-processor
          has-api: 'false'                               