name: Deploy Tennis Rankings Application Stack
on: 
  workflow_dispatch:
    inputs:
      s3-bucket:
        description: S3 bucket containing AWS Lambda binaries to deploy
        type: string
        required: true
jobs:
  deploy-player-tournament-results-service:
    name: Deploy Player Tournament Results Service
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}        
      - name: Deploy player tournament results service
        id: deploy-player-tournament-results-service
        uses: ./.github/actions/build-and-deploy-lambda
        with:
          service-name: player-tournament-results-service
          folder-name: player-tournament-results
          s3-bucket: ${{ inputs.s3-bucket }}
          s3-prefix: player-tournament-results
          has-api: 'true'       
      - name: Create Build Summary  
        run: echo "Player Tournament Results Service URL - ${{ steps.deploy-player-tournament-results-service.outputs.api-url }}" >> $GITHUB_STEP_SUMMARY
  deploy-player-rankings-service:
    name: Deploy Player Rankings Service
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}        
      - name: Deploy player rankings service
        id: deploy-player-rankings-service
        uses: ./.github/actions/build-and-deploy-lambda
        with:
          service-name: player-rankings-service
          folder-name: player-rankings
          s3-bucket: ${{ inputs.s3-bucket }}
          s3-prefix: player-rankings
          has-api: 'true'          
      - name: Create Build Summary  
        run: echo "Player Rankings Service URL - ${{ steps.deploy-player-rankings-service.outputs.api-url }}" >> $GITHUB_STEP_SUMMARY
  deploy-player-results-processor-service:
    needs: [deploy-player-tournament-results-service, deploy-player-rankings-service]
    name: Deploy Player Results Processor Service
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}        
      - name: Deploy player results processor service
        id: deploy-player-results-processor-service
        uses: ./.github/actions/build-and-deploy-lambda
        with:
          service-name: player-results-processor-service
          folder-name: player-results-processor
          s3-bucket: ${{ inputs.s3-bucket }}
          s3-prefix: player-results-processor
          has-api: 'false'                               