version: '3.0'

services:
  localstack:
    image: localstack/localstack:2.0.2
    ports:
      - '4566:4566'    
    environment: 
      - DEFAULT_REGION=ap-southeast-2
      - EDGE_PORT=4566
      - SERVICES=dynamodb
    volumes:
      - ./local-stack-scripts/init.sh:/etc/localstack/init/ready.d/init.sh  


