AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Player Tournaments Result Application Lambda and DynamoDb
Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: true
    
Resources:
  PlayerTournamentResultsApplication:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: player-tournament-results/src/
      Handler: app.playerResultsHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        CreatePlayerTournamentResult:
          Type: Api
          Properties:
            Path: /player-result
            Method: PUT
        UpdatePlayerTournamentResult:
          Type: Api
          Properties:
            Path: /player-result/{id}
            Method: PUT
        GetPlayerTournamentResult:
          Type: Api
          Properties:
            Path: /player-result
            Method: GET      
            RequestParameters:
              - method.request.querystring.firstName:
                  Required: false
                  Caching: false
              - method.request.querystring.lastName:
                  Required: false
                  Caching: false       
              - method.request.querystring.tournament:
                  Required: false
                  Caching: false     
        RemovePlayerTournamentResult:
          Type: Api
          Properties:
            Path: /player-result/{id}
            Method: DELETE                                                                           
      Policies:    
      - DynamoDBCrudPolicy:
          TableName: !Ref PlayerTournamentResultsTable      
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
  PlayerTournamentResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "player_tournment_results"
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S      
        - AttributeName: firstName
          AttributeType: S
        - AttributeName: lastName
          AttributeType: S          
        - AttributeName: tournament
          AttributeType: S 
      GlobalSecondaryIndexes:
        - IndexName: first_name-index
          KeySchema:
            - AttributeName: firstName
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: last_name-index
          KeySchema:
            - AttributeName: lastName
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: tournament-index
          KeySchema:
            - AttributeName: tournament
              KeyType: HASH
          Projection:
            ProjectionType: ALL                        
      BillingMode: PAY_PER_REQUEST  
      StreamSpecification:
        StreamViewType: NEW_IMAGE
Outputs:
  PlayerTournamentResultsApplicationUri:
    Description: API Gateway endpoint URL for Prod stage for Player Tournament Results Application
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/player-result"
    Export:
      Name: "player-tournament-results-application-url"
  PlayerTournamentResultsApplication:
    Description: Player Tournament Results Application Lambda ARN
    Value: !GetAtt PlayerTournamentResultsApplication.Arn
  PlayerTournamentResultsApplicationIamRole:
    Description: Implicit IAM Role created for Player Tournament Results Application Lambda
    Value: !GetAtt PlayerTournamentResultsApplicationRole.Arn
  PlayerTournamentResultsTableStreamArn:
    Description: Arn of the Player Tournament Results DynamoDB Table Stream
    Value: !GetAtt PlayerTournamentResultsTable.StreamArn
